components/product/ProductDetails.tsx, components/product/ProductDetailsImages.tsx, components/product/ProductVariantSelector.tsx, components/product/SimilarSelector.tsx, deno.json
=> feat: adicionado componente de seleção por similar

deno.json, sections/Images/ImageGallery.tsx
=> fix: aumento na quantidade de itens na galeria de imagens da home

components/product/ProductHighlights.tsx, static/redirect.csv
=> fix: teste redirect

components/product/ProductDetails.tsx, components/search/Filters.tsx, deno.json
=> feat: adicionado preço no pix na pdp e novos filtros no departamento

checkout/css/checkout6-custom.css, components/product/ProductDetails.tsx, components/product/SimilarSelector.tsx, deno.json
=> fix: ajuste no componente SimilarSelector e css do checkout

deno.json, loaders/RedirectsFromCsvWithEncoding.ts, manifest.gen.ts
=> feat: adicionado novo loader de redirect

redirect.csv
=> fix: ajuste no arquivo redirect

redirect.csv
=> fix: ajuste no arquivo redirect.csv

components/header/HeaderLayout.tsx, components/product/AddToCartButton.tsx, components/product/ProductDetails.tsx, components/ui/BannerCarousel.tsx, deno.json
=> feat: ajustes para melhora de performance

components/header/Buttons.tsx
=> fix: ajuste tamanho botao cart

manifest.gen.ts, sections/Seo/SeoPDPCustom.tsx
=> feat: adicionado SeoPDPCustom.tsx

sections/Images/ImageGallery.tsx
=> fix: ajuste css ImageGallery

components/GlobalTags.tsx
=> feat: add tag AdOpt

components/ui/CookieConsent.tsx
=> fix: ajuste css CookieConsent

sections/Images/ImageGallery.tsx
=> fix: ajuste no componente ImageGallery

sections/Images/ImageGallery.tsx
=> fix: slider home

sections/Images/ImageGallery.tsx
=> fix: ajuste componente slider categorie

sections/Images/ImageGallery.tsx
=> fix: correção css slider categorias

components/ui/BannerGrid.tsx, sections/Images/ImageGallery.tsx
=> fix: ajuste no slider categories

components/ui/BannerGrid.tsx, deno.json, sections/Images/ImageGallery.tsx
=> feat: revertendo a vitrine categorias

manifest.gen.ts, sections/Images/ImageGallery.tsx, sections/Images/ImageGalleryBanners.tsx
=> feat: adicionado carrossel na imageGallery

sections/Images/ImageGallery.tsx
=> fix: ajuste teste

sections/Images/ImageGallery.tsx
=> feat: ajuste teste image carousel

components/product/ProductDetails.tsx
=> 11108 - fix: corrigido nome do vendedor

.deco/blocks/Banner%20Carrosel.json, .deco/blocks/Banner%20Grid%20-%20Home.json, .deco/blocks/BannerGrid.json, .deco/blocks/Categorias%20-%20ImageGallery.json, .deco/blocks/Categories.json, .deco/blocks/Footer%20Black.json, .deco/blocks/Footer%20Global.json, .deco/blocks/Footer.json, .deco/blocks/Header%20Black.json, .deco/blocks/Header%20Global.json, .deco/blocks/Header.json, .deco/blocks/Home%20-%20Carousel.json, .deco/blocks/Home.json, .deco/blocks/Nossas%20redes%20sociais%20-%20InfoCard%2FImageGallery.json, .deco/blocks/Topbar%2Cheader%2Cnavmenu.json, .deco/blocks/pages-Home%2520Copy-32604.json, .deco/blocks/pages-Home%2520Lid-437157.json, .deco/blocks/pages-Home%2520task%252011291-150370.json, .deco/blocks/pages-institucional-c0b0ef99d3e0.json, .deco/blocks/storefront.json
=> chore:migrate-images

app-tags/deno.json, deno.json, static/tailwind.css
=> fixUpdate - update

components/product/ReviewsAndRatings/Register.tsx
---
Fix no user
---
Sem evidências.
---
---
- **Tarefa:** [TASK 11349](https://runrun.it/pt-BR/tasks/11349)
- **Design no Figma:** [Mobile](https://www.figma.com/proto/jPsW4DzegAOTeMlgWPxhtH/-11349_-Top-M%C3%B3veis--Disponibiliza%C3%A7%C3%A3o-do-Recurso-para-Avalia%C3%A7%C3%A3o-dos-Consumidores?amp%3Bamp%3Blocale=pt-br&node-id=13742-24622), [Desktop](https://www.figma.com/proto/jPsW4DzegAOTeMlgWPxhtH/-11349_-Top-M%C3%B3veis--Disponibiliza%C3%A7%C3%A3o-do-Recurso-para-Avalia%C3%A7%C3%A3o-dos-Consumidores?amp%3Bamp%3Blocale=pt-br&node-id=17743-505)
=> task/11349 - remove user

.deco/blocks/pages-account-80f202a5b269.json, components/proxy/ProxyCustom.tsx, components/proxy/ProxyIframeCustom.tsx
---
Alteração na url padrão
---
Sem evidências.
---
---
- **Tarefa:** [TASK 11349](https://runrun.it/pt-BR/tasks/11349)
- **Design no Figma:** [Mobile](https://www.figma.com/proto/jPsW4DzegAOTeMlgWPxhtH/-11349_-Top-M%C3%B3veis--Disponibiliza%C3%A7%C3%A3o-do-Recurso-para-Avalia%C3%A7%C3%A3o-dos-Consumidores?amp%3Bamp%3Blocale=pt-br&node-id=13742-24622), [Desktop](https://www.figma.com/proto/jPsW4DzegAOTeMlgWPxhtH/-11349_-Top-M%C3%B3veis--Disponibiliza%C3%A7%C3%A3o-do-Recurso-para-Avalia%C3%A7%C3%A3o-dos-Consumidores?amp%3Bamp%3Blocale=pt-br&node-id=17743-505)
=> fix/11349 - mudança na url
